// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cosmosdb_test.Repositories.Context;

#nullable disable

namespace cosmosdb_test.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260123074800_RenamedModels")]
    partial class RenamedModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cosmosdb_test.Repositories.Models.CompletedGameState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MachineMove")
                        .HasColumnType("int");

                    b.Property<int>("MatchResult")
                        .HasColumnType("int");

                    b.Property<int>("PlayerMove")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompletedGameStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
