// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cosmosdb_test.Models.Context;

#nullable disable

namespace cosmosdb_test.Migrations
{
    [DbContext(typeof(GameContextSql))]
    partial class GameContextSqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cosmosdb_test.Models.PlayedGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MachineMove")
                        .HasColumnType("int");

                    b.Property<int>("MatchResult")
                        .HasColumnType("int");

                    b.Property<int>("PlayerMove")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayedGame", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
